app/App/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from app import db

# Helpers
def create_account(username, password):
	hashed_password = bcrypt.generate_password_hash(password)
	new_account = User(username=username, password=hashed_password)
	db.session.add(new_account)
	db.session.commit()

# Models
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(80), unique=False, nullable=False)
    def __repr__(self):
        return '<User %r>' % self.username

class Post(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(80), nullable=False)
	body = db.Column(db.Text, nullable=False)
	author = db.relationship('User', backref=db.backref('posts', lazy=True))
	author_id = db.Column(db.Integer, db.ForeignKey('user.id'),nullable=False)

app/App/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField, TextAreaField
from wtforms.validators import Required, Email, EqualTo


# Define the login form (WTForms)

class LoginForm(Form):
    username    = TextField('Username', [Required(message='You need to enter a username duh')])
    password = PasswordField('Password', [Required(message='Ey whats the password')])


class PostForm(Form):
	title = TextField('Title', [Required(message="Ey you need a title")])
	body = TextAreaField('Body', [Required(message="Ey you need a title")], render_kw={"rows": 70, "cols": 70})

app/App/routes.py
# Import flask dependencies
from flask import render_template, Blueprint, request, session, flash, redirect, url_for
import flask_bcrypt

from app import db
from app.App.forms import LoginForm, PostForm
from app.App.models import User, Post

# Define the blueprint: 'auth', set its url prefix: app.url/auth
App = Blueprint('App', __name__, url_prefix='/')
# Routes

@App.route("/logout")
def sign_out():
    session.pop('username', None)
    return redirect(url_for('App.index'))

@App.route("/login", methods=['GET', 'POST'])
def sign_in():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and flask_bcrypt.check_password_hash(user.password, form.password.data):
            session['username'] = user.username
            return redirect(url_for('App.index'))
        flash('Wrong email or password', 'error-message')

    return render_template('App/login.html', form=form)

@App.route("/")
def index():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('App/index.html', posts=posts)

@App.route("/new_post", methods=['GET', 'POST'])
def new_post():
    if "username" not in session:
        return redirect(url_for('App.index'))
    form = PostForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=session["username"]).first()
        new_post = Post(title=form.title.data, body=form.body.data, author=user)
        user.posts.append(new_post)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('App.index'))



    return render_template('App/new_post.html', form=form)



if __name__ == '__main__':
    app.run(debug=True)

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)

# Import a module / component using its blueprint handler variable (mod_auth)
from app.App.routes import App as app_module
app.register_blueprint(app_module)
db.create_all()

app/templates/App/index.html
{% extends "boilerplate.html" %}

{% block content %}
  <div class="">
    <div class="row">
      <div class="col">
       <div style="width"id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{{ url_for('static', filename='img/carousel/car_1.png') }}" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h4>Welcome to</h4>
                <h1>The Greatest Bar in all of Duskval!</h1>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{{ url_for('static', filename='img/carousel/car_2.png') }}" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h1>The best you can ever experience!</h1>
                <p>People love our place so much, we almost don't have enough room <small>...in our basement</small>!</p>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{{ url_for('static', filename='img/carousel/car_3.png') }}" class="d-block w-100" alt="...">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

    </div>
    <div class="row mt-5 mb-5">
      <div class="col-3">
        <div class="container-fluid mt-4">
          <div class="row container-fluid d-flex">
            <img class="mx-auto" src="{{ url_for('static', filename='img/logo.png') }}" alt="Celeste_IRL" style="border-radius: 50%; width: 140px">
          </div>
          <div class="row d-flex">
            <div class="text-center mx-auto">
              <h3 class="text-light">Our Guarantee</h3>
              <h5 class="text-light">"Might fuck up, but gets 'shit' done"</h5>
            </div>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="row">
          <div class="container-fluid col mb-5">
            <div class="container-fluid row">
              <div class="col">
                <h2 class="text-center text-white">Founders</h2>
                <hr>
              </div>
            </div>
            <div class="container-fluid row d-flex justify-content-around">
              <div class="media">
                <img class="mr-3" src="{{ url_for('static', filename='img/celesteirl.png') }}" alt="Celeste_IRL" style="border-radius: 50%; width: 86px">
                <div class="media-body">
                  <h5 class="mt-4 text-white">Cullel Manamune</h5>
                </div>
              </div>
              <div class="media">
                <img class="mr-3" src="{{ url_for('static', filename='img/Meirl.png') }}" alt="Generic placeholder image" style="border-radius: 50%; width: 64px">
                <div class="media-body">
                  <h5 class="mt-4 text-white">Laudius Lia'thyra</h5>
                </div>
              </div>
              <div class="media">
                <img class="mr-3" src="{{ url_for('static', filename='img/ryanirl.png') }}" alt="Generic placeholder image" style="border-radius: 50%; width: 64px">
                <div class="media-body">
                  <h5 class="mt-4 text-white">Ernest Shepard</h5>
                </div>
              </div>
              <div class="media">
                <img class="mr-3" src="{{ url_for('static', filename='img/luisirl.png') }}" alt="Generic placeholder image" style="border-radius: 50%; width: 64px">
                <div class="media-body">
                  <h5 class="mt-4 text-white">Emen Payne</h5>
                </div>
              </div>
              <div class="media">
                <img class="mr-3" src="{{ url_for('static', filename='img/zacirl.png') }}" alt="Celeste_IRL" style="border-radius: 50%; width: 86px">
                <div class="media-body">
                  <h5 class="mt-4 text-white">Zach</h5>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <h3 class="text-center text-white">Meet our staff!</h3>
            <hr>
          </div>
          <div class="container-fluid row d-flex justify-content-around">
              <div class="media">
                <div class="media-body">
                  <h5 class="mt-0 text-white">Uncle Rodger</h5>
                  <p class="text-white">Don't ask where the beer comes from.</p>
                </div>
              </div>
              <div class="media">
                <div class="media-body">
                  <h5 class="mt-0 text-white">Weeliam</h5>
                  <p class="text-white">I'm not a child! I'm an adult!</p>
                </div>
              </div>
              <div class="media">
                <div class="media-body">
                  <h5 class="mt-0 text-white">Rogan</h5>
                  <p class="text-white">...</p>
                </div>
              </div>
              <div class="media">
                <div class="media-body">
                  <h5 class="mt-0 text-white">Jeff</h5>
                  <p class="text-white">My name Jeff.</p>
                </div>
              </div>
              <div class="media">
                <div class="media-body">
                  <h5 class="mt-0 text-white">Jovin</h5>
                  <p class="text-white">I show up once a month for work.</p>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
    <div class="row bg-white">
      <div class="col-6 ml-5">
        <div class="row">
          <div class="pt-3 col-4 container-fluid">
              <h1 class="text-center"><b>Crew News!</b></h1>
              {% if session["username"] %}
              <a href="{{ url_for('App.new_post') }}" class="ml-auto mr-3">
                <h5 class="pt-3 text-center">Create New Post!</h5>
              </a>
              {% endif %}
          </div>
          <div class="col">
          {% for post in posts %}
            <div class="row container mt-3 mb-3">
              <div class="col container">
              <h3 class="text-left">
                {{ post.title }}
              </h3>
                {{ post.body|safe }}
              <p>
                Written by:
                {{ post.author.username }}
              </p>
              <hr>
              </div>

            </div>
          {% endfor %}
          </div>
        </div>
      </div>
      <div class="col">
        <div class="row">
          <div class="pt-4 pb-4 col container">
              <h1 class="text-center">Menu</h1>
          </div>
        </div>
        <div class="row container-fluid">
          <div class="col d-flex flex-column">
            <div class="media mx-auto my-4">
              <img class="mr-3" src="{{ url_for('static', filename='img/uncles_best.jpg') }}" alt="Generic placeholder image" style="border-radius: 6%; width: 64px">
              <div class="media-body">
                <h5 class="mt-0">Essence of Roger</h5>
                <p>A drink made by our very own talanted Uncle Rodger!</p>
              </div>
            </div>
            <div class="media mx-auto my-4">
              <div class="media-body">
                <h5 class="mt-0 mr-4 text-right">Whisper Girl Bath Water</h5>
                A special drink created by (<small> and from</small>) Cullel herself!
              </div>
              <img class="mr-3" src="{{ url_for('static', filename='img/ggbw.jpg') }}" alt="Generic placeholder image" style="border-radius: 6%; width: 64px; height:64px">
            </div>
            <div class="media mx-auto my-4">
              <img class="mr-3" src="{{ url_for('static', filename='img/pineapple.jpg') }}" alt="Generic placeholder image" style="border-radius: 6%; width: 64px; height:64px">
              <div class="media-body">
                <h5 class="mt-0 mr-4">Ernest's Favorite</h5>
                <p>
                 Its strong that it's sure to knock you off your
                 feet, you'll start hearing bells!
                 </p>
              </div>

            </div>
            <div class="media mx-auto my-4">
              <div class="media-body">
                <h5 class="mt-0 mr-4 text-right">Rogans Blunts</h5>

              </div>
              <img class="mr-3" src="{{ url_for('static', filename='img/seth.jpg') }}" alt="Generic placeholder image" style="border-radius: 6%; width: 64px; height:64px">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/App/login.html
{% macro render_field(field) %}
  <dt class="text-white">{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

{% extends "boilerplate.html" %}

{% block content %}


<div class="container">

	<div class="row container d-flex mx-auto">
	  <div class="col">
	  	<h3 class="text-white">Hey you!</h3>
	  	<p class="text-white">
	  		This page is for Degen members only!
	  		So you better make sure you're a Degen
	  		before pressing the login button!
	  	</p>
	  </div>
	  <div class="col">
	    <legend class="text-white">Sign in</legend>
	    {% with errors = get_flashed_messages(category_filter=["error"]) %}
	    {% if errors %}
	    <div>
	    {% for error in errors %}
	    {{ error }}<br>
	    {% endfor %}
	    </div>
	    {% endif %}
	    {% endwith %}

	    {% if form.errors %}
	    <div>
	    {% for field, error in form.errors.items() %}
	    {% for e in error %}
	    {{ e }}<br>
	    {% endfor %}
	    {% endfor %}
	    </div>
	    {% endif %}
	    <form method="POST" action="{{ url_for('App.sign_in') }}" accept-charset="UTF-8" role="form">
	      {{ form.csrf_token }}
	      {{ render_field(form.username, placeholder="Your Username",
	                                  autofocus="") }}
	      {{ render_field(form.password, placeholder="Password") }}
	      <div>
	      <label class="text-white">
	      </div>
	      <button type="submit" name="submit">Sign in</button>
	    </form>
	  </div>
  </div>
</div>

{% endblock %}

app/templates/App/new_post.html
{% extends "boilerplate.html" %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col">
			<H3 class="text-white">Create new post</H3>
			<form action="" method=post>
			   {{ form.csrf_token }}
			   <dl>
			      <dt class="text-white">Title:
			      <dd>{{ form.title }}
			      <dt class="text-white">Body:
			      <dd>{{ form.body(cols="60", rows="20") }}}
			   </dl>
			   <p>
			      <button type=submit value="Publish" class="btn btn-success"> Publish</button>
			</form>
		</div>
	</div>
</div>

{% endblock %}

app/templates/boilerplate.html
<!DOCTYPE html>
<html>
  <head>
    <title>Deranged Pidgeon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>
  <body class="bg-dark" >
    <div class="container-fluid">
      <div class="row bg-white">
        <div class="col-sm p-4 d-flex">
          <a href="{{ url_for('App.index') }}" class="text-dark mr-4" style="text-decoration: none;">
            <h4>Welcome</h4>
          </a>
          <a href="" class="text-dark mr-4" style="text-decoration: none;">
            <h4> Menu </h4>
          </a>
        </div>
        <div class="col-sm p-2 pt-4">
          <a href="{{ url_for('App.index') }}" class = "text-dark" style="text-emphasis: none;">
            <h2 class="text-center"><b>The Deranged Pidgeon</b></h2>
          </a>
        </div>
        <div class="col-sm p-4 d-flex">
          <a href="" class="text-dark ml-auto mr-4" style="text-decoration: none;">
            <h4>About Us</h4>
          </a>
          <a href="" class="text-dark mr-4" style="text-decoration: none;">
            <h4>Contact</h4>
          </a>
          {% if session["username"] %}
            <a href="{{ url_for('App.sign_out') }}" class="text-dark mr-4" style="text-decoration: none;">
              <h4 class="text-danger">Sign out</h4>
            </a>
          {% else %}
          <a href="{{ url_for('App.sign_in') }}" class="text-dark mr-4" style="text-decoration: none;">
            <h4>Login</h4>
          </a>
          {% endif%}
        </div>
      </div>
      <div class="row">
    <div class="col container-fluid">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
          <ul class="flashes alert alert-warning">
            {% for message in messages %}
                <li class="text-center">{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
    {% endwith %}
    </div>
  </div>
    </div>

    {% block content %}{% endblock %}


    <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>